# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: execution.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'execution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65xecution.proto\x12\texecution\"-\n\x16\x45xecuteWorkflowRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\x05\"?\n\x17\x45xecuteWorkflowResponse\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"0\n\x18GetWorkflowStatusRequest\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\x05\"}\n\x16WorkflowStatusResponse\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\x05\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x12\n\nstarted_at\x18\x04 \x01(\t\x12\x14\n\x0c\x63ompleted_at\x18\x05 \x01(\t2\xca\x01\n\x11WorkflowExecution\x12X\n\x0f\x45xecuteWorkflow\x12!.execution.ExecuteWorkflowRequest\x1a\".execution.ExecuteWorkflowResponse\x12[\n\x11GetWorkflowStatus\x12#.execution.GetWorkflowStatusRequest\x1a!.execution.WorkflowStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'execution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEWORKFLOWREQUEST']._serialized_start=30
  _globals['_EXECUTEWORKFLOWREQUEST']._serialized_end=75
  _globals['_EXECUTEWORKFLOWRESPONSE']._serialized_start=77
  _globals['_EXECUTEWORKFLOWRESPONSE']._serialized_end=140
  _globals['_GETWORKFLOWSTATUSREQUEST']._serialized_start=142
  _globals['_GETWORKFLOWSTATUSREQUEST']._serialized_end=190
  _globals['_WORKFLOWSTATUSRESPONSE']._serialized_start=192
  _globals['_WORKFLOWSTATUSRESPONSE']._serialized_end=317
  _globals['_WORKFLOWEXECUTION']._serialized_start=320
  _globals['_WORKFLOWEXECUTION']._serialized_end=522
# @@protoc_insertion_point(module_scope)
